# ---
    parser: babel-eslint
    extends: "@cerner/terra"
    settings:
        polyfills:
            - Promise
            - Map
    env:
      jasmine: true
    rules:
        react/forbid-prop-types: off

    overrides:
        - files: "*.js"
          rules:
           import/no-cycle: off
           template-curly-spacing: off
           indent:
               - error
               - 2
               - ignoredNodes:
                  - TemplateLiteral
           strict: off
           func-names: off
           no-underscore-dangle: off
           no-console: off
           import/no-extraneous-dependencies: off
           no-param-reassign: off

        - files: "**/scripts/**/*.js"
          rules:
            import/no-extraneous-dependencies: off
            import/no-unresolved: off
            import/extensions: off

        - files: "**/*.config.js"
          rules:
            import/no-extraneous-dependencies: off

        - files: "**/*.conf.js"
          rules:
            import/no-extraneous-dependencies: off

        - files: "**/webpack/**/*.js"
          rules:
            import/no-extraneous-dependencies: off
            import/no-unresolved: off
            import/extensions: off

        - files: "**/tests/**/*.js"
          rules:
            import/no-extraneous-dependencies: off
            import/no-unresolved: off
            import/extensions: off

        - files: "**/tests/**/*.jsx"
          rules:
            import/no-extraneous-dependencies: off
            import/no-unresolved: off
            import/extensions: off

        - files: "**/dev/**/*.js"
          rules:
            import/no-extraneous-dependencies: off
            import/no-unresolved: off

        - files: "**/dev-site/**/*.js"
          rules:
            import/no-extraneous-dependencies: off
            import/no-unresolved: off
            import/extensions: off
            prefer-rest-params: off
            no-restricted-syntax: off

        - files: "*.doc.jsx"
          rules:
            import/no-webpack-loader-syntax: off
            import/first: off
            import/no-duplicates: off

        - files: "packages/terra-graphs-docs/*.jsx"
          rules:
            import/no-extraneous-dependencies: off
            import/no-unresolved: off
            import/extensions: off

        - files: "packages/terra-graphs-docs/src/**/*js"
          rules:
           import/no-unresolved: off
           import/extensions: off


        - files: "*.conf.js"
          rules:
            import/no-extraneous-dependencies: off
            import/no-unresolved: off
            import/extensions: off

        - files: "*.config.js"
          rules:
            import/no-extraneous-dependencies: off
            import/no-unresolved: off
            import/extensions: off
