    extends: "@cerner/stylelint-config-terra"
    rules: 
      scss/at-mixin-pattern: "^(terra-)[a-z]+([a-z0-9-]+[a-z0-9]+)?$"
      selector-no-qualifying-type: null
      property-no-vendor-prefix: null
      terra/custom-property-name: null
      terra/custom-property-namespace: null
      terra/custom-property-pseudo-selectors: null
