---
#CI will run on all pushes and PRs to verify validity of the code
name: CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']
  schedule:
    - cron: '0 1 * * SUN'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Project
        uses: actions/checkout@v3
      - name: Setup Project
        uses: ./.github/actions/setup
      - if: github.event_name == 'pull_request'
        name: Danger
        uses: danger/danger-js@9.1.8
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # https://github.com/danger/danger-js/issues/557#issuecomment-664851950
          DANGER_DISABLE_TRANSPILATION: true
      - name: Linting Project
        run: |
          npm run lint
      - name: Testing Project
        run: |
          npm run jest
          npm run karma
      - name: Build Project
        run: |
          npm run build
          npm run build:dist
  wdio:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        form-factor: [tiny, small, medium, large, huge, enormous]
      
    steps:
      - name: Checkout Project
        uses: actions/checkout@v3
      - name: Setup Project
        uses: ./.github/actions/setup
      - name: Build Project
        run: |
          npm run build
          npm run build:dist
      - name: Run WDIO Tests for form factor ${{ matrix.form-factor}}
        run: FORM_FACTOR=${{ matrix.form-factor}} npm run wdio-default
